name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - "*/*"

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Check formatting
        run: npx prettier --check "./**/*.{ts,tsx}"
