name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - "*/*"

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint

      - name: Run tests
        run: bun test

      - name: Check formatting
        run: bunx prettier --check "./**/*.{ts,tsx}"
