name: Mirror to SourceHut

on:
  push:
    branches: ['*']

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SOURCEHUT_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan git.sr.ht >> ~/.ssh/known_hosts
      
      - name: Mirror to SourceHut
        run: |
          git remote add sourcehut git@git.sr.ht:~tomupom/tom-so
          git push sourcehut --all --force
          git push sourcehut --tags --force
